sudo: required
dist: bionic

language: csharp
mono: none
dotnet: 2.0.0
solution: DepotDownloader.sln

install:
    - dotnet restore DepotDownloader.sln

script:
    - dotnet build DepotDownloader.sln

notifications:
    irc:
        channels:
            - "irc.gamesurge.net#opensteamworks"
        on_success: never
        on_failure: always

cache:
    directories:
        - "~/.local/share/NuGet/Cache"
