name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-should-have-happened
    attributes:
      label: What did you expect to happen?
      placeholder: I expected that...
    validations:
      required: true
  - type: textarea
    id: what-actually-happened
    attributes:
      label: Instead of that, what actually happened?
      placeholder: ... but instead, what happened was...
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Which operating system are you running on?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true
  - type: input
    id: dotnet-version
    attributes:
      label: Version
      description: What version of DepotDownloader are you running on?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Is there anything else that you think we should know?
    validations:
      required: false
