name: Feature Request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks, we appreciate good ideas!
  - type: textarea
    id: problem-area
    attributes:
      label: What problem is this feature trying to solve?
      placeholder: I'm really frustrated when...
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: How would you like it to be solved?
      placeholder: I think that it could be solved by...
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Have you considered any alternative solutions
      placeholder: I did think that that it also could be solved by ..., but...
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Is there anything else that you think we should know?
    validations:
      required: false
